server.port: 8082
server:
  servlet:
    context-path: /colts
spring:
  datasource:
    url: jdbc:mysql://${172.18.0.2:localhost}:3307/db
    username: user
    password: password
  jpa:
    hibernate.ddl-auto: update
    
          
          
#url: jdbc:mysql:///db1157